/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.21
 * Generated at: 2015-05-05 01:15:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class clock_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:replace", org.apache.taglibs.standard.functions.Functions.class, "replace", new Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<link href=\"/ClockPortlet2/public/jClocksGMT-master/css/jClocksGMT.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"/ClockPortlet2/css/clock.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"/ClockPortlet2/public/jquery-1.11.2/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("\t<script src=\"/ClockPortlet2/public/jClocksGMT-master/js/jClocksGMT.js\"></script>\r\n");
      out.write("\t<script src=\"/ClockPortlet2/public/jClocksGMT-master/js/jquery.rotate.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t//init world clocks\r\n");
      out.write("\t\t\t$('.clock_container').each(function() {\r\n");
      out.write("\t\t\t\t$(this).jClocksGMT({\r\n");
      out.write("\t\t\t\t\toffset: $(this).attr('offset')\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- World Clock -->\r\n");
      out.write("    <div id=\"clock_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:replace(city, ' ', '_')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
      out.write("\" class=\"clock_container\" offset=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offset}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("        <div class=\"lbl\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${city}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\r\n");
      out.write("        <div class=\"clockHolder\">\r\n");
      out.write("            <div class=\"rotatingWrapper\"><img class=\"hour\" src=\"/ClockPortlet2/public/jClocksGMT-master/images/clock_hour.png\" /></div>\r\n");
      out.write("            <div class=\"rotatingWrapper\"><img class=\"min\" src=\"/ClockPortlet2/public/jClocksGMT-master/images/clock_min.png\" /></div>\r\n");
      out.write("            <div class=\"rotatingWrapper\"><img class=\"sec\" src=\"/ClockPortlet2/public/jClocksGMT-master/images/clock_sec.png\" /></div>\r\n");
      out.write("            <img class=\"clock\" src=\"/ClockPortlet2/public/jClocksGMT-master/images/clock_face.png\" />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"digital\">\r\n");
      out.write("            <span class=\"hr\"></span><span class=\"minute\"></span> <span class=\"period\"></span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
